package secrets

import (
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"os"
	"path/filepath"
)

const (
	// DefaultPasswordLength is the length of generated passwords
	DefaultPasswordLength = 24
)

// GenerateSecrets creates the secrets directory and generates required secret files
func GenerateSecrets(outputDir string) error {
	// Create secrets directory with 0700 permissions
	if err := os.MkdirAll(outputDir, 0700); err != nil {
		return fmt.Errorf("failed to create secrets directory: %w", err)
	}

	// Generate admin password
	adminPassword := GeneratePassword(DefaultPasswordLength)
	if err := writeSecret(outputDir, "admin_password.txt", adminPassword); err != nil {
		return err
	}

	// Create placeholder for DKIM private key (actual key from Phase 4 dns-setup tool)
	dkimPlaceholder := "# DKIM private key will be generated by darkpipe-dns-setup tool\n# See: darkpipe-dns-setup --domain example.com\n"
	if err := writeSecret(outputDir, "dkim_private_key.pem", dkimPlaceholder); err != nil {
		return err
	}

	return nil
}

// GeneratePassword generates a cryptographically secure random password
func GeneratePassword(length int) string {
	// Use base64 encoding of random bytes for alphanumeric password
	// We need length * 3/4 bytes to get length characters (due to base64 encoding overhead)
	numBytes := (length * 3) / 4
	if numBytes < length {
		numBytes = length
	}

	bytes := make([]byte, numBytes)
	if _, err := rand.Read(bytes); err != nil {
		// Fallback to a simpler method if crypto/rand fails
		panic(fmt.Sprintf("failed to generate random password: %v", err))
	}

	// Encode to base64 and trim to desired length
	password := base64.RawURLEncoding.EncodeToString(bytes)
	if len(password) > length {
		password = password[:length]
	}

	return password
}

// ReadSecret reads a secret from a file
func ReadSecret(dir, name string) (string, error) {
	path := filepath.Join(dir, name)
	data, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("failed to read secret %s: %w", name, err)
	}

	return string(data), nil
}

// ListSecrets lists all secret files in a directory
func ListSecrets(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("failed to list secrets directory: %w", err)
	}

	secrets := []string{}
	for _, entry := range entries {
		if !entry.IsDir() {
			secrets = append(secrets, entry.Name())
		}
	}

	return secrets, nil
}

// writeSecret writes a secret to a file with 0600 permissions
func writeSecret(dir, name, content string) error {
	path := filepath.Join(dir, name)
	if err := os.WriteFile(path, []byte(content), 0600); err != nil {
		return fmt.Errorf("failed to write secret %s: %w", name, err)
	}

	return nil
}
